//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public long UserID { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
    
        public virtual RegisterUser RegisterUser { get; set; }
    }
}
